cooking/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipe/', include('recipe.urls'))
]

recipe/urls.py
from django.conf.urls import url
from . import views

app_name = 'recipe'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.details, name='details'),
    url(r'^save/$', views.save, name='save'),
    url(r'^(?P<res_id>[0-9]+)/$', views.display, name='display')
]

migrate/models.py
from django.db import models

# Create your models here.

recipe/models.py
from django.db import models
from django.utils import timezone


class Recipe(models.Model):
    name = models.CharField(max_length=40)
    ingredients = models.CharField(max_length=200)
    process = models.TextField()
    prep_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

migrate/views.py
from django.shortcuts import render

# Create your views here.

recipe/views.py
from django.shortcuts import render
from .models import Recipe
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    recipe_list = Recipe.objects.all()
    return render(request, 'recipe/index.html', {'recipe_list':recipe_list})


def details(request):
    Recipe.objects.create(name=request.POST['name'],
                          ingredients=request.POST['ingredients'],
                          process=request.POST['process']
                          )
    return HttpResponseRedirect(reverse('recipe:index'))
    return render(request, 'recipe/create.html')


def save(request):
    Recipe.objects.create(name= request.POST['name'],
                          ingredients=request.POST['ingredients'],
                          process=request.POST['process']
                         )
    return HttpResponseRedirect(reverse('recipe:index'))


def display(request, res_id):
    recipe = Recipe.objects.get(pk=res_id)
    return render(request, 'recipe/display.html', {'recipe': recipe})

recipe/templates/recipe/create.html
<h1> Create Recipe </h1>

<form action="{%url 'recipe:save' %}"  method="post">
    {% csrf_token %}
    name:<br> <input type="text" name="name"><br>
    ingredients:<br> <input type="text" name="ingredients"><br>
    process    :<br> <input type="text" name="process"><br>
    <input type="submit" value="save">
</form>

recipe/templates/recipe/display.html
 <b>Hey Welcome To Details About Recipes</b></br>
<h5/>
 name : {{ recipe.name }}<br>
 ingredients : {{ recipe.ingredients }}<br>
 process : {{ recipe.process }}
</h5>
 <a href="/recipe/">Back</a>

recipe/templates/recipe/index.html
<b>Recipes Menu</b></br>
{% if recipe_list %}
    <ul>
    {% for res in recipe_list %}
        <li><a href="/recipe/{{res.id}}">{{ res.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}
<a href="{%url 'recipe:details' %}"> Create Recipe </a>